name: cctv_kota_banda_aceh
description: "CCTV Kota Banda Aceh"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  webview_flutter_web: ^0.2.2+1
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  webview_flutter: ^4.4.2
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  video_player: ^2.9.2
  url_launcher: ^6.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
